root@datawarehouse:/home/nashehannafii/extraction-tools# cat push.sh 
#!/usr/bin/env bash
set -euo pipefail

# push.sh - commit and push current changes to origin main
# Usage:
#   ./push.sh update         => commit with autogenerated update timestamp message and push
#   ./push.sh "my message"   => commit with provided message and push

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 update|<commit message>"
  exit 1
fi

cmd="$1"
shift || true

if [ "$cmd" = "update" ]; then
  msg="update: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
else
  # allow multi-word messages
  msg="$cmd"
  if [ "$#" -gt 0 ]; then
    msg="$msg $*"
  fi
fi

# move to repo root if inside a git worktree
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$repo_root" ]; then
  cd "$repo_root"
fi

echo "Staging changes..."
git add -A

if git diff --cached --quiet; then
  echo "No staged changes to commit. Will still attempt to push current HEAD to origin/main."
else
  echo "Committing: $msg"
  git commit -m "$msg"
fi

remote="origin"
branch="main"

echo "Pushing to ${remote}/${branch}..."
git push "$remote" HEAD:"$branch"

echo "Done. Pushed to ${remote}/${branch}."