<html
    lang="en"
    data-layout="vertical"
    data-topbar="light"
    data-sidebar="dark"
    data-sidebar-size="sm-hover"
    data-sidebar-image="none"
    data-bs-theme="light"
    data-body-image="img-1"
    data-preloader="enable"
    data-layout-position="fixed">